# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
    ]
